# Generated by Django 3.0 on 2020-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
